;;; -*- Mode: LISP; Base: 10; Syntax: ANSI-Common-Lisp; Package: VGLT -*-
;;; Copyright (c) 2021 by Symbolics Pte. Ltd. All rights reserved.
(in-package #:vglt)

(defparameter base-url "http://raw.githubusercontent.com/vega/vega-datasets/master/data/"
  "Base URL for datasets included in Vega")

(defvar *vega-datasets* '(annual-precip anscombe barley budget budgets burtin cars countries crimea driving earthquakes flare-dependencies flare flights-10k flights-200k flights-20k flights-2k flights-5k football gapminder income jobs londonBoroughs londonCentroids londonTubeLines miserables monarchs movies normal-2d obesity ohlc penguins points political-contributions population udistrict unemployment-across-industries uniform-2d us-10m us-state-capitals volcano weather wheat world-110m airports birdstrikes co2-concentration disasters flights-3m flights-airport gapminder-health-income github iowa-electricity la-riots lookup_groups lookup_people population_engineers_hurricanes seattle-weather-hourly-normals seattle-weather sp500-2000 sp500 stocks us-employment weather windvectors zipcodes unemployment flights-200k)
 "All Vega example data sets")

;;; Data


(defvar annual-precip "http://raw.githubusercontent.com/vega/vega-datasets/master/data/annual-precip.json")
(defvar anscombe "http://raw.githubusercontent.com/vega/vega-datasets/master/data/anscombe.json")
(defvar barley "http://raw.githubusercontent.com/vega/vega-datasets/master/data/barley.json")
(defvar budget "http://raw.githubusercontent.com/vega/vega-datasets/master/data/budget.json")
(defvar budgets "http://raw.githubusercontent.com/vega/vega-datasets/master/data/budgets.json")
(defvar burtin "http://raw.githubusercontent.com/vega/vega-datasets/master/data/burtin.json")
(defvar cars "http://raw.githubusercontent.com/vega/vega-datasets/master/data/cars.json")
(defvar countries "http://raw.githubusercontent.com/vega/vega-datasets/master/data/countries.json")
(defvar crimea "http://raw.githubusercontent.com/vega/vega-datasets/master/data/crimea.json")
(defvar driving "http://raw.githubusercontent.com/vega/vega-datasets/master/data/driving.json")
(defvar earthquakes "http://raw.githubusercontent.com/vega/vega-datasets/master/data/earthquakes.json")
(defvar flare-dependencies "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flare-dependencies.json")
(defvar flare "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flare.json")
(defvar flights-10k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-10k.json")
(defvar flights-200k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-200k.json")
(defvar flights-20k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-20k.json")
(defvar flights-2k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-2k.json")
(defvar flights-5k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-5k.json")
(defvar football "http://raw.githubusercontent.com/vega/vega-datasets/master/data/football.json")
(defvar gapminder "http://raw.githubusercontent.com/vega/vega-datasets/master/data/gapminder.json")
(defvar income "http://raw.githubusercontent.com/vega/vega-datasets/master/data/income.json")
(defvar jobs "http://raw.githubusercontent.com/vega/vega-datasets/master/data/jobs.json")
(defvar londonBoroughs "http://raw.githubusercontent.com/vega/vega-datasets/master/data/londonBoroughs.json")
(defvar londonCentroids "http://raw.githubusercontent.com/vega/vega-datasets/master/data/londonCentroids.json")
(defvar londonTubeLines "http://raw.githubusercontent.com/vega/vega-datasets/master/data/londonTubeLines.json")
(defvar miserables "http://raw.githubusercontent.com/vega/vega-datasets/master/data/miserables.json")
(defvar monarchs "http://raw.githubusercontent.com/vega/vega-datasets/master/data/monarchs.json")
(defvar movies "http://raw.githubusercontent.com/vega/vega-datasets/master/data/movies.json")
(defvar normal-2d "http://raw.githubusercontent.com/vega/vega-datasets/master/data/normal-2d.json")
(defvar obesity "http://raw.githubusercontent.com/vega/vega-datasets/master/data/obesity.json")
(defvar ohlc "http://raw.githubusercontent.com/vega/vega-datasets/master/data/ohlc.json")
(defvar penguins "http://raw.githubusercontent.com/vega/vega-datasets/master/data/penguins.json")
(defvar points "http://raw.githubusercontent.com/vega/vega-datasets/master/data/points.json")
(defvar political-contributions "http://raw.githubusercontent.com/vega/vega-datasets/master/data/political-contributions.json")
(defvar population "http://raw.githubusercontent.com/vega/vega-datasets/master/data/population.json")
(defvar udistrict "http://raw.githubusercontent.com/vega/vega-datasets/master/data/udistrict.json")
(defvar unemployment-across-industries "http://raw.githubusercontent.com/vega/vega-datasets/master/data/unemployment-across-industries.json")
(defvar uniform-2d "http://raw.githubusercontent.com/vega/vega-datasets/master/data/uniform-2d.json")
(defvar us-10m "http://raw.githubusercontent.com/vega/vega-datasets/master/data/us-10m.json")
(defvar us-state-capitals "http://raw.githubusercontent.com/vega/vega-datasets/master/data/us-state-capitals.json")
(defvar volcano "http://raw.githubusercontent.com/vega/vega-datasets/master/data/volcano.json")
(defvar weather "http://raw.githubusercontent.com/vega/vega-datasets/master/data/weather.json")
(defvar wheat "http://raw.githubusercontent.com/vega/vega-datasets/master/data/wheat.json")
(defvar world-110m "http://raw.githubusercontent.com/vega/vega-datasets/master/data/world-110m.json")

(defvar airports "http://raw.githubusercontent.com/vega/vega-datasets/master/data/airports.csv")
(defvar birdstrikes "http://raw.githubusercontent.com/vega/vega-datasets/master/data/birdstrikes.csv")
(defvar co2-concentration "http://raw.githubusercontent.com/vega/vega-datasets/master/data/co2-concentration.csv")
(defvar disasters "http://raw.githubusercontent.com/vega/vega-datasets/master/data/disasters.csv")
(defvar flights-3m "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-3m.csv")
(defvar flights-airport "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-airport.csv")
(defvar gapminder-health-income "http://raw.githubusercontent.com/vega/vega-datasets/master/data/gapminder-health-income.csv")
(defvar github "http://raw.githubusercontent.com/vega/vega-datasets/master/data/github.csv")
(defvar iowa-electricity "http://raw.githubusercontent.com/vega/vega-datasets/master/data/iowa-electricity.csv")
(defvar la-riots "http://raw.githubusercontent.com/vega/vega-datasets/master/data/la-riots.csv")
(defvar lookup_groups "http://raw.githubusercontent.com/vega/vega-datasets/master/data/lookup_groups.csv")
(defvar lookup_people "http://raw.githubusercontent.com/vega/vega-datasets/master/data/lookup_people.csv")
(defvar population_engineers_hurricanes "http://raw.githubusercontent.com/vega/vega-datasets/master/data/population_engineers_hurricanes.csv")
(defvar seattle-weather-hourly-normals "http://raw.githubusercontent.com/vega/vega-datasets/master/data/seattle-weather-hourly-normals.csv")
(defvar seattle-weather "http://raw.githubusercontent.com/vega/vega-datasets/master/data/seattle-weather.csv")
(defvar sp500-2000 "http://raw.githubusercontent.com/vega/vega-datasets/master/data/sp500-2000.csv")
(defvar sp500 "http://raw.githubusercontent.com/vega/vega-datasets/master/data/sp500.csv")
(defvar stocks "http://raw.githubusercontent.com/vega/vega-datasets/master/data/stocks.csv")
(defvar us-employment "http://raw.githubusercontent.com/vega/vega-datasets/master/data/us-employment.csv")
(defvar weather "http://raw.githubusercontent.com/vega/vega-datasets/master/data/weather.csv")
(defvar windvectors "http://raw.githubusercontent.com/vega/vega-datasets/master/data/windvectors.csv")
(defvar zipcodes "http://raw.githubusercontent.com/vega/vega-datasets/master/data/zipcodes.csv")

(defvar unemployment "http://raw.githubusercontent.com/vega/vega-datasets/master/data/unemployment.tsv")
(defvar flights-200k "http://raw.githubusercontent.com/vega/vega-datasets/master/data/flights-200k.arrow")

